# Generated by Django 4.2.7 on 2024-04-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_category_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=None),
        ),
    ]
