# Generated by Django 4.2.7 on 2024-04-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categories',
        ),
    ]
