# Generated by Django 4.2.7 on 2024-03-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_category',
            field=models.CharField(choices=[('indoor', 'indoor'), ('outdoor', 'outdoor')], max_length=50),
        ),
    ]
