# Generated by Django 4.2.7 on 2024-03-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tag_order_customer_order_product_order_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='TAGS',
        ),
        migrations.AddField(
            model_name='products',
            name='TAGS',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
