# Generated by Django 4.2.7 on 2024-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_order_tags_products_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_category',
            field=models.CharField(blank=True, choices=[('indoor', 'indoor'), ('outdoor', 'outdoor')], max_length=50),
        ),
    ]
